# _config.yml
title: "Ian Martins"
description: "Data, Cloud & Analytics Enthusiast"
# The base configuration for your Jekyll site

# If you want to disable Jekyll's default theme, uncomment:
# theme: null
